### ISSUE TITLE
How do you run it?

### ISSUE THREAD

**Issue by hoodeddcoder** [gemichelst/veveshooter#1]
Hey is there a way you can show us how to run it? A youtube tutorial or detailed instructions. Thanks!

**Comment by gemichelst** [comment]
clone the repo:
`git clone git@github.com:gemichelst/veveshooter.git`

change into the cloned repo:
`cd veveshooter`

install the python dependencies
`python3 -m pip install ... ... ... ....`

plugin your android phones (with activated dev mode)
and run the code inside veveshooter dir:
`./veveshooter`

open browserurl: [http://localhost:8000](http://localhost:8000)

done. ;)
